stages:
  - test
  - deploy

testing:
  stage: test
  script:
    - make test
  only:
    - merge_requests
  allow_failure: false

deploy-docs:
  variables:
    CLOUDFLARE_API_TOKEN: $CLOUDFLARE_API_TOKEN
    CLOUDFLARE_ACCOUNT_ID: $CLOUDFLARE_ACCOUNT_ID
  stage: deploy
  script:
    - npm i @cloudflare/wrangler -g
    - make docs-html
    - wrangler pages publish ./docs/build/html --project-name=your-website --branch=main
  only:
    - master
  allow_failure: true
