[tool.isort]
profile = "black"
sections = [
    "STDLIB",
    "THIRDPARTY",
    "FIRSTPARTY",
    "LOCALFOLDER",
]

[tool.isort.imports]
"src.io" = "src.io"
"src.logger" = "src.logger"
"src.storage" = "src.storage"
"src.steps" = "src.steps"
"src.pipeline" = "src.pipeline"
"src.utils" = "src.utils"

[tool.pyright]
extraPaths = ["src"]
exclude = ["**/__init__.py"]
venv = "env"
typeCheckingMode = "strict"
reportMissingTypeStubs = false
reportUnnecessaryIsInstance = false

[tool.flake8]
max-line-length = 120
exclude = [".git", "__pycache__"]
extend-ignore = ["E203"]
per-file-ignores = ["__init__.py:F401"]
ban-relative-imports = "parents"
spellcheck-targets = "comments"