[tool.isort]
profile = "black"

[tool.pyright]
extraPaths = ["src"]
venv = "env"
typeCheckingMode = "strict"
reportMissingTypeStubs = false

[tool.flake8]
max-line-length = 120
exclude = [".git", "__pycache__"]
extend-ignore = ["E203"]
per-file-ignores = ["__init__.py:F401"]
ban-relative-imports = "parents"
spellcheck-targets = "comments"